In [3]:
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json
#When you are using your own key, replace the sandbox url with the on ein the documentation.
url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
parameters = {
  'start':'1',
  'limit':'20',
  'convert':'USD'
}
# Here replace the key with the key that you have
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': 'fe43d1a8-158d-43e0-8d1f-b002a79d0aaa',
}

session = Session()
session.headers.update(headers)

try:
  response = session.get(url, params=parameters)
  data = json.loads(response.text)
  #To test in sagemaker, for time being I'm commenting all the print comments
  #print(data)
except (ConnectionError, Timeout, TooManyRedirects) as e:
  print(e)
#So, initially when you start running this, you get a warning message that says that the data limit must be increased.
# for this, go to anaconda prompt and type the msg
#jupyter notebook --NotebookApp.iopub_data_rate_limit=1e10 --(And after this, it just open up a new page and in that it runs)
"""
We are making use of the Request library to start a session to do an API call. We are importing the JSON library
as the data is formatted in JSON. The url parameter is used to state the url from which we are scraping data and it
always loads latest data, and paramters variable to start and when to stop scraping the data. We later use the headers to
input the key, the the type of data format that must be accepted. We later write a try statement after opening a session and
throw an error if anything goes unexpected variable is used to mention.
"""

'\nWe are making use of the Request library to start a session to do an API call. We are importing the JSON library \nas the data is formatted in JSON. The url parameter is used to state the url from which we are scraping data and it \nalways loads latest data, and paramters variable to start and when to stop scraping the data. We later use the headers to \ninput the key, the the type of data format that must be accepted. We later write a try statement after opening a session and \nthrow an error if anything goes unexpected variable is used to mention. \n'

In [4]:
# The type in which the data is formatted
# supposed keys are 'status', 'data'
type(data)

dict

In [5]:
#we try to convert the dictionary to a dataframe
# Using pandas to normalize the JSON-like object and create a DataFrame
#The rest of the information is just status, but the actual key we want is "data"
!pip install --upgrade numexpr
import pandas as pd
pd.set_option('display.max_columns', None)
df = pd.json_normalize(data['data'])

Requirement already satisfied: numexpr in /usr/local/lib/python3.10/dist-packages (2.8.8)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from numexpr) (1.23.5)

In [6]:
# Now, we automate the process of API calls
#we create a column to to store the time at which data is collected/updated
df['timestamp'] = pd.to_datetime('now')

<ipython-input-6-bc6394ddf3ae>:3: FutureWarning: The parsing of 'now' in pd.to_datetime without `utc=True` is deprecated. In a future version, this will match Timestamp('now') and Timestamp.now()
  df['timestamp'] = pd.to_datetime('now')

In [7]:
df
# retrieving col names
#col_names = df.columns.tolist()
#print(col_names)

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,infinite_supply,platform,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,tvl_ratio,last_updated,quote.USD.price,quote.USD.volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.name,platform.symbol,platform.slug,platform.token_address,timestamp
0,1,Bitcoin,BTC,bitcoin,10704,2010-07-13T00:00:00.000Z,"[mineable, pow, sha-256, store-of-value, state...",2.100000e+07,1.959815e+07,1.959815e+07,False,NaN,1,NaN,NaN,None,2024-01-14T02:09:00.000Z,42727.301060,1.878693e+10,-57.2686,-0.063939,-0.103017,-3.086333,-0.623160,20.568864,56.946244,8.373761e+11,49.6520,8.972733e+11,None,2024-01-14T02:09:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-01-14 02:10:51.683049
1,1027,Ethereum,ETH,ethereum,8241,2015-08-07T00:00:00.000Z,"[pos, smart-contracts, ethereum-ecosystem, coi...",NaN,1.201812e+08,1.201812e+08,True,NaN,2,NaN,NaN,None,2024-01-14T02:09:00.000Z,2564.065311,1.138822e+10,-52.7576,-0.166410,1.268840,14.076067,11.578184,29.952195,63.971902,3.081525e+11,18.2681,3.081525e+11,None,2024-01-14T02:09:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-01-14 02:10:51.683049
2,825,Tether USDt,USDT,tether,71288,2015-02-25T00:00:00.000Z,"[payments, stablecoin, asset-backed-stablecoin...",NaN,9.501084e+10,9.860296e+10,True,NaN,3,NaN,NaN,None,2024-01-14T02:08:00.000Z,0.999966,3.630705e+10,-50.1296,0.014649,0.024419,-0.065108,-0.009840,-0.022997,-0.016464,9.500759e+10,5.6335,9.859959e+10,None,2024-01-14T02:08:00.000Z,1027.0,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7,2024-01-14 02:10:51.683049
3,1839,BNB,BNB,bnb,2008,2017-07-25T00:00:00.000Z,"[marketplace, centralized-exchange, payments, ...",NaN,1.516898e+08,1.516898e+08,False,NaN,4,NaN,NaN,None,2024-01-14T02:08:00.000Z,302.420607,7.904430e+08,-33.1618,0.329647,2.322431,-1.719326,19.897222,23.998323,43.520654,4.587413e+10,2.7195,4.587413e+10,None,2024-01-14T02:08:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-01-14 02:10:51.683049
4,5426,Solana,SOL,solana,613,2020-04-10T00:00:00.000Z,"[pos, platform, solana-ecosystem, cms-holdings...",NaN,4.325476e+08,5.670603e+08,True,NaN,5,NaN,NaN,None,2024-01-14T02:09:00.000Z,96.245602,1.809859e+09,-38.0450,1.640843,5.150230,1.722808,27.596871,68.171126,334.869667,4.163081e+10,2.4680,5.457706e+10,None,2024-01-14T02:09:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-01-14 02:10:51.683049
5,52,XRP,XRP,xrp,1199,2013-08-04T00:00:00.000Z,"[medium-of-exchange, enterprise-solutions, arr...",1.000000e+11,5.426682e+10,9.998801e+10,False,NaN,6,NaN,NaN,None,2024-01-14T02:09:00.000Z,0.574380,6.455573e+08,-61.8539,0.227408,0.875712,0.861061,-10.084683,-8.378798,17.675058,3.116976e+10,1.8478,5.743797e+10,None,2024-01-14T02:09:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-01-14 02:10:51.683049
6,3408,USDC,USDC,usd-coin,16186,2018-10-08T00:00:00.000Z,"[medium-of-exchange, stablecoin, asset-backed-...",NaN,2.547544e+10,2.547544e+10,False,NaN,7,NaN,NaN,None,2024-01-14T02:09:00.000Z,1.000270,4.390082e+09,-52.8873,0.027686,-0.009921,0.025963,0.006831,0.021644,0.007113,2.548231e+10,1.5107,2.548231e+10,None,2024-01-14T02:09:00.000Z,1027.0,Ethereum,ETH,ethereum,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,2024-01-14 02:10:51.683049
7,2010,Cardano,ADA,cardano,1023,2017-10-01T00:00:00.000Z,"[dpos, pos, platform, research, smart-contract...",4.500000e+10,3.538963e+10,3.652824e+10,False,NaN,8,NaN,NaN,None,2024-01-14T02:08:00.000Z,0.546341,3.373664e+08,-51.3167,0.296999,0.723060,3.930612,-15.252333,53.178022,120.099139,1.933480e+10,1.1465,2.458534e+10,None,2024-01-14T02:08:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-01-14 02:10:51.683049
8,5805,Avalanche,AVAX,avalanche,636,2020-07-13T00:00:00.000Z,"[defi, smart-contracts, three-arrows-capital-p...",7.200000e+08,3.666432e+08,4.346761e+08,False,NaN,9,NaN,NaN,None,2024-01-14T02:08:00.000Z,36.057551,4.705761e+08,-44.7512,0.065644,2.005917,3.219106,-7.736481,106.932384,288.942117,1.322026e+10,0.7837,2.596144e+10,None,2024-01-14T02:08:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-01-14 02:10:51.683049
9,74,Dogecoin,DOGE,dogecoin,872,2013-12-15T00:00:00.000Z,"[mineable, pow, scrypt, medium-of-exchange, me...",NaN,1.426422e+11,1.426422e+11,True,NaN,10,NaN,NaN,None,2024-01-14T02:09:00.000Z,0.080829,2.749343e+08,-55.0785,0.441837,0.982482,-0.224072,-17.765441,11.261346,35.800542,1.152959e+10,0.6835,1.152959e+10,None,2024-01-14T02:09:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-01-14 02:10:51.683049
10,1958,TRON,TRX,tron,895,2017-09-13T00:00:00.000Z,"[media, payments, tron-ecosystem, layer-1, dwf...",NaN,8.824072e+10,8.824072e+10,True,NaN,11,7.165966e+10,8.309145e+09,None,2024-01-14T02:08:00.000Z,0.115953,6.139046e+08,71.3337,0.663958,8.891030,11.476056,9.458401,12.825973,33.484690,1.023177e+10,0.6066,1.023177e+10,None,2024-01-14T02:08:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-01-14 02:10:51.683049
11,6636,Polkadot,DOT,polkadot-new,661,2020-08-19T00:00:00.000Z,"[substrate, polkadot, binance-chain, polkadot-...",NaN,1.324329e+09,1.399361e+09,True,NaN,12,NaN,NaN,None,2024-01-14T02:08:00.000Z,7.543892,1.836263e+08,-48.8510,-0.004761,-0.264266,5.096245,0.281047,44.710595,101.003535,9.990592e+09,0.5923,1.055663e+10,None,2024-01-14T02:08:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-01-14 02:10:51.683049
12,3890,Polygon,MATIC,polygon,1239,2019-04-28T00:00:00.000Z,"[pos, platform, enterprise-solutions, zero-kno...",1.000000e+10,9.562653e+09,1.000000e+10,False,NaN,13,NaN,NaN,None,2024-01-14T02:08:00.000Z,0.878384,2.968851e+08,-55.5559,0.494478,2.441554,5.332279,0.424703,-5.717922,69.386753,8.399683e+09,0.4980,8.783842e+09,None,2024-01-14T02:08:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-01-14 02:10:51.683049
13,1975,Chainlink,LINK,chainlink,1566,2017-09-20T00:00:00.000Z,"[platform, defi, oracles, smart-contracts, sub...",1.000000e+09,5.681000e+08,1.000000e+09,False,NaN,14,NaN,NaN,None,2024-01-14T02:08:00.000Z,14.385230,2.777764e+08,-52.8603,0.567480,2.537924,5.863240,-4.948842,1.994942,92.904097,8.172249e+09,0.4846,1.438523e+10,None,2024-01-14T02:08:00.000Z,1027.0,Ethereum,ETH,ethereum,0x514910771af9ca656af840dff83e8264ecf986ca,2024-01-14 02:10:51.683049
14,11419,Toncoin,TON,toncoin,187,2021-08-26T13:40:22.000Z,"[pos, layer-1, ftx-bankruptcy-estate, dwf-labs...",NaN,3.456641e+09,5.101106e+09,True,NaN,15,3.414167e+09,7.170045e+09,None,2024-01-14T02:09:00.000Z,2.100086,4.457758e+07,-17.0229,-0.138930,-0.532529,-3.688707,-4.780038,-7.928586,8.600349,7.259246e+09,0.4303,1.071276e+10,None,2024-01-14T02:09:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-01-14 02:10:51.683049
15,8916,Internet Computer,ICP,internet-computer,201,2021-03-23T00:00:00.000Z,"[platform, ai-big-data, collectibles-nfts, def...",NaN,4.554211e+08,5.132373e+08,True,NaN,16,4.554211e+08,6.061272e+09,None,2024-01-14T02:08:00.000Z,13.309161,1.897746e+08,-4.0810,4.507699,8.140068,7.758318,112.691570,214.394096,320.086406,6.061272e+09,0.3593,6.830758e+09,None,2024-01-14T02:08:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-01-14 02:10:51.683049
16,5994,Shiba Inu,SHIB,shiba-inu,723,2020-08-01T00:00:00.000Z,"[memes, ethereum-ecosystem, doggone-doggerel]",NaN,5.892906e+14,5.895347e+14,False,NaN,17,NaN,NaN,None,2024-01-14T02:08:00.000Z,0.000010,1.247787e+08,-37.8925,0.258257,2.743576,2.488781,-1.581727,17.239574,40.610669,5.798960e+09,0.3438,5.801362e+09,None,2024-01-14T02:08:00.000Z,1027.0,Ethereum,ETH,ethereum,0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce,2024-01-14 02:10:51.683049
17,4943,Dai,DAI,multi-collateral-dai,2980,2019-11-22T00:00:00.000Z,"[defi, stablecoin, asset-backed-stablecoin, et...",NaN,5.347889e+09,5.347889e+09,True,NaN,18,NaN,NaN,None,2024-01-14T02:08:00.000Z,0.999999,2.505483e+08,-22.4721,-0.003537,-0.013347,-0.000482,0.059311,0.064630,-0.041896,5.347882e+09,0.3171,5.347882e+09,None,2024-01-14T02:08:00.000Z,1027.0,Ethereum,ETH,ethereum,0x6b175474e89094c44da98b954eedeac495271d0f,2024-01-14 02:10:51.683049
18,2,Litecoin,LTC,litecoin,1079,2013-04-28T00:00:00.000Z,"[mineable, pow, scrypt, medium-of-exchange]",8.400000e+07,7.409063e+07,8.400000e+07,False,NaN,19,NaN,NaN,None,2024-01-14T02:09:00.000Z,71.568426,3.607026e+08,-62.3793,-0.774725,-0.155564,8.769947,-1.346434,1.323457,15.606597,5.302549e+09,0.3143,6.011748e+09,None,2024-01-14T02:09:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-01-14 02:10:51.683049
19,1831,Bitcoin Cash,BCH,bitcoin-cash,825,2017-07-23T00:00:00.000Z,"[mineable, pow, sha-256, marketplace, medium-o...",2.100000e+07,1.961316e+07,1.961316e+07,False,NaN,20,NaN,NaN,None,2024-01-14T02:08:00.000Z,257.695197,2.757322e+08,-60.8862,1.783677,0.295370,8.724414,8.943077,11.632130,18.969381,5.054216e+09,0.2996,5.411599e+09,None,2024-01-14T02:08:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-01-14 02:10:51.683049

In [8]:
def automate_api():
    #when the function call happens, the variable df is considered as a local variable, and hence it raises an error saying
    # that it is used before assignment, hence we declare it as glabal
    global df
    url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
    parameters = {
      'start':'1',
      'limit':'20',
      'convert':'USD'
    }
# Here replace the key with the key that you have
    headers = {
      'Accepts': 'application/json',
      'X-CMC_PRO_API_KEY': 'fe43d1a8-158d-43e0-8d1f-b002a79d0aaa',
    }

    session = Session()
    session.headers.update(headers)

    try:
      response = session.get(url, params=parameters)
      data = json.loads(response.text)
      #print(data)
    except (ConnectionError, Timeout, TooManyRedirects) as e:
      print(e)
    #Here we already have the original data frame setup at top, so the data we get must be appended to the existing dataframe
    #after retrieving data, it is normalized and stored in the dataframe with the time stamp

    # commenting all this as I want to copy the data to csv
    pd.set_option('display.max_columns', None)
    df_latest = pd.json_normalize(data['data'])
    df_latest['timestamp'] = pd.to_datetime('now')
    #Now, here as you want to append data to the original dataframe i.e df
    #df = df.append(df_latest, ignore_index = True)
    df = pd.concat([df, df_latest], ignore_index=True)
    #If this doesn't work try running the same jypyter statement in the prompt.

    #df = pd.json_normalize(data['data'])
    #df['timestamp'] = pd.to_datetime('now')
    #df

    #if not os.path.isfile(r'"C:\Users\hp\Downloads\API.csv'):
     #   df.to_csv(r'"C:\Users\hp\Downloads\API.csv', header='column_names')
    #else:
    #    df.to_csv(r'"C:\Users\hp\Downloads\API.csv', mode='a', header=False)

In [9]:
#
import os
from time import time
from time import sleep
try:
    # Your code here
    for i in range(5):
        automate_api()
        print("Process completed!")
    #After calling the function, the script waits for 5 seconds before starting the loop again
        sleep(5)
    #exit()
except Exception as e:
    print(f"An error occurred: {e}")

#for i in range(5):
   # automate_api()
   # print("Process completed!")
    #After calling the function, the script waits for 5 seconds before starting the loop again
   # sleep(5)
#exit()

<ipython-input-8-5c525938f50c>:32: FutureWarning: The parsing of 'now' in pd.to_datetime without `utc=True` is deprecated. In a future version, this will match Timestamp('now') and Timestamp.now()
  df_latest['timestamp'] = pd.to_datetime('now')

Process completed!

<ipython-input-8-5c525938f50c>:32: FutureWarning: The parsing of 'now' in pd.to_datetime without `utc=True` is deprecated. In a future version, this will match Timestamp('now') and Timestamp.now()
  df_latest['timestamp'] = pd.to_datetime('now')

Process completed!

<ipython-input-8-5c525938f50c>:32: FutureWarning: The parsing of 'now' in pd.to_datetime without `utc=True` is deprecated. In a future version, this will match Timestamp('now') and Timestamp.now()
  df_latest['timestamp'] = pd.to_datetime('now')

Process completed!

<ipython-input-8-5c525938f50c>:32: FutureWarning: The parsing of 'now' in pd.to_datetime without `utc=True` is deprecated. In a future version, this will match Timestamp('now') and Timestamp.now()
  df_latest['timestamp'] = pd.to_datetime('now')

Process completed!

<ipython-input-8-5c525938f50c>:32: FutureWarning: The parsing of 'now' in pd.to_datetime without `utc=True` is deprecated. In a future version, this will match Timestamp('now') and Timestamp.now()
  df_latest['timestamp'] = pd.to_datetime('now')

Process completed!

In [10]:
#df

In [11]:
# One thing I noticed was the scientific notation. I like it, but I want to be able to see the numbers in this case

pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [12]:
#df
# I wrote this, just to understand the data
#first_20_rows = df.head(22)

# Display the first 20 rows
#print(first_20_rows)

In [13]:
df3 = df.groupby('name', sort=False)[['quote.USD.percent_change_1h','quote.USD.percent_change_24h','quote.USD.percent_change_7d','quote.USD.percent_change_30d','quote.USD.percent_change_60d','quote.USD.percent_change_90d','num_market_pairs','circulating_supply','total_supply','quote.USD.price','quote.USD.volume_24h', 'quote.USD.volume_change_24h','quote.USD.market_cap', 'quote.USD.market_cap_dominance', 'quote.USD.fully_diluted_market_cap']].mean()
#df3

In [14]:
#stacking them up now to perform useful visualizations, we need to pivot it
df4 = df3.stack()
df4

name
Bitcoin       quote.USD.percent_change_1h                  -0.05963
              quote.USD.percent_change_24h                 -0.10684
              quote.USD.percent_change_7d                  -3.07759
              quote.USD.percent_change_30d                 -0.55438
              quote.USD.percent_change_60d                 20.59636
                                                         ...
Bitcoin Cash  quote.USD.volume_24h                  275787574.86528
              quote.USD.volume_change_24h                 -60.88187
              quote.USD.market_cap                 5054628556.15650
              quote.USD.market_cap_dominance                0.29967
              quote.USD.fully_diluted_market_cap   5412040689.74000
Length: 300, dtype: float64

In [15]:
type(df4)

pandas.core.series.Series

In [16]:
df5 = df4.to_frame(name='values')
#df5
#type(df5)

In [17]:
#You have to make this dynamic(like the count has to be retrived)
df5_count = df5.count()['values']
#print(df5_count)
# REMEMBER THAT YOU HAVE TO GENERATE THIS COUNT VARIABLE DYNAMICALLY
#

In [18]:
# indexing the dataset now
#Because of how it's structured above we need to set an index. I don't want to pass a column as an index for this dataframe
#So I'm going to create a range and pass that as the dataframe. You can make this more dynamic, but I'm just going to hard code it


index = pd.Index(range(df5_count))

# Set the above DataFrame index object as the index
# using set_index() function
df6 = df5.reset_index()
#df6

# If it only has the index and values try doing reset_index like "df5.reset_index()"

In [19]:
# Change the column name

df7 = df6.rename(columns={'level_1': 'percent_change'})
#df7

In [20]:
df7['percent_change'] = df7['percent_change'].replace(['quote.USD.percent_change_24h','quote.USD.percent_change_7d','quote.USD.percent_change_30d','quote.USD.percent_change_60d','quote.USD.percent_change_90d','num_market_pairs','quote.USD.price','quote.USD.market_cap','quote.USD.market_cap_dominance','quote.USD.fully_diluted_market_cap','quote.USD.percent_change_1h'],['24h','7d','30d','60d','90d','market_pairs','price_in_USD','market_cap','market_cap_dominance','fully_diluted_market_cap','1hr'])
#df7

In [23]:
#trying to write the final data frame to a csv file, let's see if this works!
#Yep, this works
# we changed the mode to W--new data gets added.
if not os.path.isfile(r'"\API.csv'):
    df7.to_csv(r'API.csv', header='column_names')
else:
    df7.to_csv(r'API.csv', mode='w', header=False)

In [ ]:
# First way to schedule
# 2nd method is by using AWS lambda and sage maker to

# New section